param(
    [Parameter(Mandatory = $true, HelpMessage = 'Root directory of the SDK (contains .project/.cproject)')]
    [string]$SdkRoot,

    [ValidateSet('tx', 'rx', 'at', 'selfie')]
    [string]$Target = 'rx',

    [ValidateSet('txrx', 'txrx_selfie', 'allinone')]
    [string]$RomType = 'txrx_selfie',

    [ValidateSet('flash', 'real', 'default')]
    [string]$EfuseSource = 'default',

    [string]$FlashAddr = '0x76000',

    [ValidateSet('0', '1')]
    [string]$FixedPins = '1',

    [string]$WorkspaceDir = '',

    # Eclipse build target format: <ProjectName>/<BuildConfigName>.
    [string]$BuildTarget = 'Robin/flash_on_rom_lib',

    # Path to TelinkIoTStudio.exe. Default: read from TELINK_IDE_EXE env var, or fallback.
    [string]$IdeExe = '',

    # Directory to collect renamed build artifacts. Default: <SDK_ROOT>\build_variants.
    [string]$OutputDir = '',

    # Optional output base name without extension. Default is auto-generated.
    [string]$OutputName = ''
)

$ErrorActionPreference = 'Stop'

# ── Resolve SDK root ──────────────────────────────────────────────────
$SdkRoot = (Resolve-Path $SdkRoot).Path

if (-not (Test-Path (Join-Path $SdkRoot '.project')) -or -not (Test-Path (Join-Path $SdkRoot '.cproject'))) {
    Write-Error "$SdkRoot does not look like an SDK root (missing .project/.cproject)"
    exit 2
}

$BuildConfig = Join-Path $SdkRoot 'telink_ble\vendor\blueLight\robin_build_config.h'

# ── Map options to macros ─────────────────────────────────────────────
$TargetValue = switch ($Target) {
    'tx' { 1 }
    'rx' { 2 }
    'at' { 3 }
    'selfie' { 4 }
}

$RomTypeValue = switch ($RomType) {
    'txrx_selfie' { 0 }
    'txrx' { 2 }
    'allinone' { 3 }
}

switch ($EfuseSource) {
    'flash' { $EfuseRuntime = 1; $EfuseFlash = 1 }
    'real' { $EfuseRuntime = 1; $EfuseFlash = 0 }
    'default' { $EfuseRuntime = 0; $EfuseFlash = 0 }
}

$FlashAddrValue = [Convert]::ToUInt32(($FlashAddr -replace '^0x', ''), 16)
$FlashAddrNorm = ('0x{0:X8}UL' -f $FlashAddrValue)
$FlashAddrName = ('0x{0:X5}' -f $FlashAddrValue)

# ── Generate build config header ──────────────────────────────────────
$ConfigText = @"
/* Auto-generated by robin_build_variant.ps1. */
#pragma once
#define ROBIN_FW_TARGET $TargetValue
#define ROBIN_ROM_TYPE $RomTypeValue
#define ROBIN_CFG_SELFIE_FIXED_PINS $FixedPins
#define ROBIN_CFG_ENABLE_EFUSE_RUNTIME $EfuseRuntime
#define ROBIN_CFG_ENABLE_EFUSE_FLASH_MIRROR $EfuseFlash
#define ROBIN_CFG_EFUSE_FLASH_MIRROR_ADDR $FlashAddrNorm
"@

if (Test-Path $BuildConfig) {
    Remove-Item -Path $BuildConfig -Force
}
[System.IO.File]::WriteAllText($BuildConfig, ($ConfigText + [Environment]::NewLine), [System.Text.Encoding]::ASCII)

# ── Resolve IDE path ──────────────────────────────────────────────────
if ([string]::IsNullOrWhiteSpace($IdeExe)) {
    $IdeExe = $env:TELINK_IDE_EXE
}
if ([string]::IsNullOrWhiteSpace($IdeExe)) {
    $IdeExe = 'E:\TelinkIoTStudio\TelinkIoTStudio.exe'
}

# ── Resolve workspace ─────────────────────────────────────────────────
if ([string]::IsNullOrWhiteSpace($WorkspaceDir)) {
    $WorkspaceDir = Join-Path (Split-Path $SdkRoot -Parent) 'telink_IDE'
}
if (-not (Test-Path $WorkspaceDir)) {
    New-Item -ItemType Directory -Path $WorkspaceDir | Out-Null
}
$WorkspaceDir = (Resolve-Path $WorkspaceDir).Path

# ── Resolve output dir ────────────────────────────────────────────────
if ([string]::IsNullOrWhiteSpace($OutputDir)) {
    $OutputDir = Join-Path $SdkRoot 'build_variants'
}
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir | Out-Null
}
$OutputDir = (Resolve-Path $OutputDir).Path

# ── Build ─────────────────────────────────────────────────────────────
$BuildLog = Join-Path $SdkRoot 'robin_build_variant.log'
$BuildStart = (Get-Date).AddSeconds(-3)

$status = 0
$BuildWasRun = $false
if (Test-Path $IdeExe) {
    $BuildWasRun = $true
    Write-Host "Running Telink headless build:"
    Write-Host "  IDE: $IdeExe"
    Write-Host "  -data: $WorkspaceDir"
    Write-Host "  -import: $SdkRoot"
    Write-Host "  -cleanBuild: $BuildTarget"
    Write-Host "  log: $BuildLog"

    $oldErrorActionPreference = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'

    & $IdeExe --launcher.suppressErrors -nosplash `
        -application org.eclipse.cdt.managedbuilder.core.headlessbuild `
        -data $WorkspaceDir `
        -import $SdkRoot `
        -cleanBuild $BuildTarget `
        2>&1 | ForEach-Object { $_.ToString() } | Tee-Object -FilePath $BuildLog

    $status = $LASTEXITCODE
    $ErrorActionPreference = $oldErrorActionPreference
} else {
    Write-Warning "Telink IDE not found at $IdeExe"
    Write-Host "Generated $BuildConfig only. Set --ide-exe or the TELINK_IDE_EXE environment variable."
    $status = 1
}

# ── Collect artifacts ─────────────────────────────────────────────────
$CopiedBin = $null
$CopiedLst = $null

if ($status -eq 0) {
    $BuildConfigName = ($BuildTarget -split '/', 2)[-1]

    $binCandidates = Get-ChildItem -Path $SdkRoot -Recurse -Include *.bin -File -ErrorAction SilentlyContinue |
        Where-Object {
            $_.FullName -notlike "*$([System.IO.Path]::DirectorySeparatorChar)efuse_flash_out$([System.IO.Path]::DirectorySeparatorChar)*" -and
            $_.FullName -notlike "*$([System.IO.Path]::DirectorySeparatorChar)build_variants$([System.IO.Path]::DirectorySeparatorChar)*" -and
            $_.FullName -like "*$BuildConfigName*" -and
            $_.LastWriteTime -ge $BuildStart
        } |
        Sort-Object LastWriteTime -Descending

    if (-not $binCandidates -or $binCandidates.Count -eq 0) {
        $binCandidates = Get-ChildItem -Path $SdkRoot -Recurse -Include *.bin -File -ErrorAction SilentlyContinue |
            Where-Object {
                $_.FullName -notlike "*$([System.IO.Path]::DirectorySeparatorChar)efuse_flash_out$([System.IO.Path]::DirectorySeparatorChar)*" -and
                $_.FullName -notlike "*$([System.IO.Path]::DirectorySeparatorChar)build_variants$([System.IO.Path]::DirectorySeparatorChar)*" -and
                $_.FullName -like "*$BuildConfigName*"
            } |
            Sort-Object LastWriteTime -Descending
    }

    $SourceBin = $binCandidates | Select-Object -First 1

    if ($SourceBin) {
        $Timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
        if ([string]::IsNullOrWhiteSpace($OutputName)) {
            $OutputBaseName = "${Target}_${RomType}_${EfuseSource}_${FlashAddrName}_fixed${FixedPins}_${Timestamp}"
        } else {
            $OutputBaseName = $OutputName -replace '[\\/:*?"<>| ]', '_'
        }

        $DestBin = Join-Path $OutputDir ($OutputBaseName + '.bin')
        Copy-Item -Path $SourceBin.FullName -Destination $DestBin -Force
        $CopiedBin = Get-Item $DestBin

        $lstCandidates = Get-ChildItem -Path $SdkRoot -Recurse -Include *.lst -File -ErrorAction SilentlyContinue |
            Where-Object {
                $_.FullName -notlike "*$([System.IO.Path]::DirectorySeparatorChar)build_variants$([System.IO.Path]::DirectorySeparatorChar)*" -and
                $_.FullName -like "*$BuildConfigName*" -and
                $_.LastWriteTime -ge $BuildStart
            } |
            Sort-Object LastWriteTime -Descending

        $SourceLst = $lstCandidates | Select-Object -First 1
        if ($SourceLst) {
            $DestLst = Join-Path $OutputDir ($OutputBaseName + '.lst')
            Copy-Item -Path $SourceLst.FullName -Destination $DestLst -Force
            $CopiedLst = Get-Item $DestLst
        }
    } else {
        Write-Warning "Build succeeded, but no .bin artifact was found under build config '$BuildConfigName'."
    }
}

# ── Summary ───────────────────────────────────────────────────────────
Write-Host ''
Write-Host 'Robin build variant summary'
Write-Host "  SDK root:  $SdkRoot"
Write-Host "  target:    $Target"
Write-Host "  rom type:  $RomType"
Write-Host "  eFuse:     $EfuseSource"
Write-Host "  flash addr: $FlashAddrNorm"
Write-Host "  workspace: $WorkspaceDir"
Write-Host "  build:     $(if ($status -eq 0) { 'success' } elseif ($BuildWasRun) { 'failed' } else { 'generated-config-only' })"
if ($status -ne 0 -and $BuildWasRun) {
    Write-Host "  See build log: $BuildLog"
}
if ($CopiedBin) {
    $rel = $CopiedBin.FullName.Substring($SdkRoot.Length + 1)
    Write-Host "  copied bin: $rel ($($CopiedBin.Length) bytes)"
}
if ($CopiedLst) {
    $rel = $CopiedLst.FullName.Substring($SdkRoot.Length + 1)
    Write-Host "  copied lst: $rel ($($CopiedLst.Length) bytes)"
}

Write-Host ''
Write-Host 'Newest build artifacts:'
Get-ChildItem -Path $SdkRoot -Recurse -Include *.bin, *.lst -File -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 20 |
    ForEach-Object {
        $rel = $_.FullName.Substring($SdkRoot.Length + 1)
        Write-Host "  artifact: $rel ($($_.Length) bytes) $($_.LastWriteTime)"
    }

exit $status