#!/usr/bin/env bash
set -euo pipefail

# Defaults – can be overridden via CLI or environment variables.
target="rx"
rom_type="txrx_selfie"
efuse_source="flash"
flash_addr="0x76000"
fixed_pins="1"
sdk_root=""
build_target="Robin/flash_on_rom_lib"
ide_exe="${TELINK_IDE_EXE:-/home/test/Telink/TelinkIoTStudio}"
workspace_dir=""

usage() {
  cat <<USAGE
Usage: $0 --sdk-root PATH [options]

Build the TC BLE Lite SDK (flash_on_rom_lib) for a given target.

REQUIRED:
  --sdk-root PATH       Root directory of the SDK (contains .project/.cproject)

OPTIONS:
  --target tx|rx|at|selfie          Firmware target (default: rx)
  --rom-type txrx|txrx_selfie|allinone
                                    ROM type (default: txrx_selfie)
  --efuse-source flash|real|default
                                    eFuse source (default: flash)
  --flash-addr 0x76000              Flash mirror address (default: 0x76000)
  --fixed-pins 0|1                  Fixed pins (default: 1)
  --build-target NAME               Eclipse build target (default: Robin/flash_on_rom_lib)
  --ide-exe PATH                    TelinkIoTStudio executable (env: TELINK_IDE_EXE)
  --workspace PATH                  Eclipse workspace directory (default: \$SDK_ROOT/../telink_IDE)
  -h, --help                        Show this help

EXAMPLES:
  $0 --sdk-root /home/test/code/tc_ble_lite_sdk-1.2.2_allinone
  $0 --sdk-root /home/test/code/my_sdk --target tx --efuse-source real
  TELINK_IDE_EXE=/opt/TelinkIoTStudio $0 --sdk-root /path/to/sdk

USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)       target="$2";       shift 2 ;;
    --rom-type)     rom_type="$2";     shift 2 ;;
    --efuse-source) efuse_source="$2"; shift 2 ;;
    --flash-addr)   flash_addr="$2";   shift 2 ;;
    --fixed-pins)   fixed_pins="$2";   shift 2 ;;
    --sdk-root)     sdk_root="$2";     shift 2 ;;
    --build-target) build_target="$2"; shift 2 ;;
    --ide-exe)      ide_exe="$2";      shift 2 ;;
    --workspace)    workspace_dir="$2"; shift 2 ;;
    -h|--help)      usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

# ── Validate required args ──────────────────────────────────────────────
if [[ -z "$sdk_root" ]]; then
  echo "error: --sdk-root is required" >&2
  usage >&2
  exit 2
fi

sdk_root="$(cd "$sdk_root" && pwd)"

if [[ ! -f "$sdk_root/.project" || ! -f "$sdk_root/.cproject" ]]; then
  echo "error: $sdk_root does not look like an SDK root (missing .project/.cproject)" >&2
  exit 2
fi

BUILD_CONFIG="$sdk_root/telink_ble/vendor/blueLight/robin_build_config.h"

# ── Map options to macros ───────────────────────────────────────────────
case "$target" in
  tx)     target_value=1 ;;
  rx)     target_value=2 ;;
  at)     target_value=3 ;;
  selfie) target_value=4 ;;
  *)      echo "Invalid --target: $target" >&2; exit 2 ;;
esac

case "$rom_type" in
  txrx_selfie) rom_type_value=0 ;;
  txrx)        rom_type_value=2 ;;
  allinone)    rom_type_value=3 ;;
  *)           echo "Invalid --rom-type: $rom_type" >&2; exit 2 ;;
esac

case "$efuse_source" in
  flash)   efuse_runtime=1; efuse_flash=1 ;;
  real)    efuse_runtime=1; efuse_flash=0 ;;
  default) efuse_runtime=0; efuse_flash=0 ;;
  *)       echo "Invalid --efuse-source: $efuse_source" >&2; exit 2 ;;
esac

case "$fixed_pins" in 0|1) ;; *) echo "Invalid --fixed-pins: $fixed_pins" >&2; exit 2 ;; esac

flash_addr_norm=$(python3 - <<PY
value = int("$flash_addr", 0)
print(f"0x{value:08X}UL")
PY
)

# Generate the build config header
cat > "$BUILD_CONFIG" <<CFG
/* Auto-generated by robin_build_variant.sh. */
#pragma once
#define ROBIN_FW_TARGET ${target_value}
#define ROBIN_ROM_TYPE ${rom_type_value}
#define ROBIN_CFG_SELFIE_FIXED_PINS ${fixed_pins}
#define ROBIN_CFG_ENABLE_EFUSE_RUNTIME ${efuse_runtime}
#define ROBIN_CFG_ENABLE_EFUSE_FLASH_MIRROR ${efuse_flash}
#define ROBIN_CFG_EFUSE_FLASH_MIRROR_ADDR ${flash_addr_norm}
CFG

# ── Resolve IDE / workspace paths ───────────────────────────────────────
if [[ -z "$workspace_dir" ]]; then
  workspace_dir="$sdk_root/../telink_IDE"
fi
mkdir -p "$workspace_dir"

if [[ "${OSTYPE:-}" == "msys" || "${OSTYPE:-}" == "cygwin" || "${OSTYPE:-}" == "win32" ]]; then
  ide_exe="${ide_exe:-E:/TelinkIoTStudio/TelinkIoTStudio.exe}"
  workspace_dir="file:/$(cygpath -m "$workspace_dir")"
  project_path="$(cygpath -m "$sdk_root")"
else
  project_path="$sdk_root"
fi

# ── Build ───────────────────────────────────────────────────────────────
status=0
"$ide_exe" --launcher.suppressErrors -nosplash \
  -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
  -data "$workspace_dir" \
  -import "$project_path" \
  -cleanBuild "$build_target" || status=$?

# ── Summary ─────────────────────────────────────────────────────────────
printf '\nRobin build variant summary\n'
printf '  SDK root:  %s\n' "$sdk_root"
printf '  target:    %s\n' "$target"
printf '  rom type:  %s\n' "$rom_type"
printf '  eFuse:     %s\n' "$efuse_source"
printf '  flash addr: %s\n' "$flash_addr_norm"
printf '  build:     %s\n' "$([[ $status -eq 0 ]] && echo success || echo failed)"

while IFS= read -r file; do
  [[ -f "$file" ]] || continue
  size=$(wc -c < "$file" | tr -d ' ')
  printf '  artifact: %s (%s bytes)\n' "${file#$sdk_root/}" "$size"
done < <(find "$sdk_root" -type f \( -name '*.bin' -o -name '*.lst' \) -path '*flash_on_rom_lib*' 2>/dev/null | sort | tail -20)

exit "$status"